# WARNING: This file is a DEMO ONLY and is intentionally committed for testing purposes.
# WARNING: Do NOT commit real passwords.

key: ddphotos-sample-key-all

site:
  password: allgood
  hint: What say you now?

albums:
  uganda:
    password: gorilla
    hint: A big brown ape
  antarctica:
    password: penguin
